const ACTIONS_LOGGER = {
  CREATE_USER: "CREATE_USER",
  DELETE_USER: "DELETE_USER",
  UPDATE_USER: "UPDATE_USER",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
};

const LEVELS_LOGGER = {
  INFO: "info",
  WARN: "warn",
  ERROR: "error",
};

export { ACTIONS_LOGGER, LEVELS_LOGGER };
